import {
  TreePine,
  Hammer,
  HardHat,
  Layers,
  Grid3X3,
  Droplets,
  Waves,
  Truck,
  Package,
} from "lucide-react";

export const COMPANY = {
  name: "Sunrise Landscape General Contractor Inc",
  shortName: "Sunrise Landscape",
  phone: "(425) 903-7666",
  phoneHref: "tel:+14259037666",
  email: "sunriselsgenconllc@gmail.com",
  address: "Marysville, WA",
  hours: "Monday - Saturday: 7:00 AM - 6:00 PM",
  hoursClosed: "Sunday: Closed",
  yearsExperience: 12,
  projectsCompleted: 500,
  citiesServed: 8,
  logo: "/images/%232_Sunrise-Landscape-General-Contrator-Inc.png",
};

export const SERVICES = [
  {
    title: "Landscaping",
    slug: "landscaping",
    icon: TreePine,
    shortDescription: "Complete landscape design, installation, and maintenance for residential and commercial properties.",
    description: "Transform your outdoor space with our comprehensive landscaping services. From initial design to final installation, we create beautiful, functional landscapes that enhance your property's curb appeal and value. Our team specializes in native Pacific Northwest plantings, garden bed design, sod installation, and seasonal maintenance programs.",
    features: [
      "Custom landscape design & planning",
      "Garden bed creation & planting",
      "Sod & seed installation",
      "Mulching & ground cover",
      "Tree & shrub planting",
      "Seasonal clean-up & maintenance",
      "Irrigation system installation",
      "Lawn renovation & restoration",
    ],
    images: [
      "/images/new+landscaping+design-1920w.jpg",
      "/images/new+garden+beds-1920w.jpg",
      "/images/landscape+digging-ff70d53c-1920w.jpg",
    ],
    heroImage: "/images/new+landscaping+design-1920w.jpg",
  },
  {
    title: "Hardscaping",
    slug: "hardscaping",
    icon: Hammer,
    shortDescription: "Patios, outdoor living spaces, and decorative stone work that stands the test of time.",
    description: "Elevate your outdoor living experience with our expert hardscaping services. We design and build stunning patios, outdoor kitchens, fire pits, and decorative stone features that seamlessly blend with your landscape. Our craftsmanship ensures lasting beauty and structural integrity for years to come.",
    features: [
      "Patio design & construction",
      "Outdoor kitchen & living areas",
      "Fire pit & fireplace installation",
      "Decorative stone walls & borders",
      "Steps & stairways",
      "Natural stone placement",
      "Outdoor lighting integration",
      "Pergolas & shade structures",
    ],
    images: [
      "/images/stone+pathways-1920w.jpg",
      "/images/g-1-1363w.jpg",
      "/images/g2-1363w.jpg",
    ],
    heroImage: "/images/stone+pathways-1920w.jpg",
  },
  {
    title: "Concrete Work",
    slug: "concrete",
    icon: HardHat,
    shortDescription: "Driveways, foundations, sidewalks, and decorative concrete solutions.",
    description: "Our concrete specialists deliver exceptional results for both functional and decorative concrete projects. From driveways and foundations to stamped and stained decorative concrete, we ensure every pour meets the highest standards of quality and durability. We handle projects of all sizes throughout Snohomish County.",
    features: [
      "Driveway installation & repair",
      "Foundation work",
      "Sidewalks & pathways",
      "Stamped & decorative concrete",
      "Concrete pad installation",
      "Curbing & edging",
      "Concrete sealing & finishing",
      "Demolition & removal",
    ],
    images: [
      "/images/g3-1363w.jpg",
      "/images/g4-1363w.jpg",
      "/images/img-5-1920w.jpg",
    ],
    heroImage: "/images/g3-1363w.jpg",
  },
  {
    title: "Retaining Walls",
    slug: "retaining-walls",
    icon: Layers,
    shortDescription: "Engineered retaining walls for erosion control and beautiful terraced landscapes.",
    description: "Protect your property and create usable space with our professionally engineered retaining walls. Whether you need erosion control on a slope, decorative terracing, or structural support, our team builds retaining walls that are both functional and aesthetically pleasing. We work with a variety of materials including natural stone, concrete block, and timber.",
    features: [
      "Structural retaining walls",
      "Decorative garden walls",
      "Terraced landscape design",
      "Erosion control solutions",
      "Natural stone walls",
      "Concrete block systems",
      "Timber retaining walls",
      "Drainage integration",
    ],
    images: [
      "/images/curved+retaining+wall-1920w.jpg",
      "/images/curved+retaining+walls-1920w.jpg",
      "/images/retaining+wall+beds-1920w.jpg",
      "/images/Retaining+wall+land+prep-1920w.jpg",
    ],
    heroImage: "/images/curved+retaining+wall-1920w.jpg",
  },
  {
    title: "Pavers & Walkways",
    slug: "pavers",
    icon: Grid3X3,
    shortDescription: "Custom paver installations for walkways, driveways, and outdoor living areas.",
    description: "Add elegance and functionality to your property with our custom paver installations. We specialize in interlocking pavers for walkways, driveways, patios, and pool decks. With a wide selection of materials, patterns, and colors, we create unique designs that complement your home's architecture and landscape.",
    features: [
      "Interlocking paver driveways",
      "Walkway & pathway installation",
      "Paver patio construction",
      "Pool deck pavers",
      "Paver repair & restoration",
      "Permeable paver systems",
      "Custom patterns & borders",
      "Base preparation & grading",
    ],
    images: [
      "/images/stone+pathways-1920w.jpg",
      "/images/img-6-1920w.jpg",
      "/images/img-7-1920w.jpg",
    ],
    heroImage: "/images/stone+pathways-1920w.jpg",
  },
  {
    title: "Drainage Systems",
    slug: "drainage",
    icon: Droplets,
    shortDescription: "French drains, catch basins, and water management to protect your property.",
    description: "Protect your property from water damage with our professional drainage solutions. The Pacific Northwest's heavy rainfall demands proper water management. We design and install comprehensive drainage systems including French drains, catch basins, channel drains, and grading solutions that keep your property dry and your foundation safe.",
    features: [
      "French drain installation",
      "Catch basin systems",
      "Channel & trench drains",
      "Downspout redirection",
      "Yard grading & swales",
      "Sump pump installation",
      "Foundation waterproofing",
      "Erosion prevention",
    ],
    images: [
      "/images/landscape+digging-ff70d53c-1920w.jpg",
      "/images/Excavation-1920w.jpg",
      "/images/img-5-1920w.jpg",
    ],
    heroImage: "/images/landscape+digging-ff70d53c-1920w.jpg",
  },
  {
    title: "Pool Restoration",
    slug: "pool-restoration",
    icon: Waves,
    shortDescription: "Complete pool & spa restoration — resurfacing, tile work, and deck renovation.",
    description: "Bring your pool or spa back to life with our comprehensive restoration services. As one of the few contractors in the Snohomish County area offering pool restoration, we specialize in resurfacing, tile repair, coping replacement, and complete pool deck renovation. Whether your pool needs cosmetic updates or structural repairs, our team delivers exceptional results.",
    features: [
      "Pool resurfacing & replastering",
      "Tile repair & replacement",
      "Coping stone installation",
      "Pool deck restoration",
      "Spa & hot tub renovation",
      "Equipment upgrades",
      "Waterline tile installation",
      "Complete pool makeovers",
    ],
    images: [
      "/images/Pool+Before-1920w.jpg",
      "/images/Pool+After-1920w.jpg",
      "/images/pool+restoration+services-1920w.jpg",
      "/images/pool+tile-1920w.jpg",
      "/images/swimming+pool+restoration+services-1920w.jpg",
      "/images/Spa+Before-1920w.jpg",
      "/images/Spa+After-b9408c57-1920w.jpg",
    ],
    heroImage: "/images/pool+restoration+services-1920w.jpg",
    highlight: true,
  },
  {
    title: "Excavation",
    slug: "excavation",
    icon: Truck,
    shortDescription: "Site preparation, grading, trenching, and land clearing for any project.",
    description: "Our experienced excavation team handles projects of all sizes, from small residential grading to large commercial site preparation. With our fleet of heavy equipment, we provide efficient and precise excavation, trenching, grading, and demolition services throughout the greater Snohomish County area.",
    features: [
      "Site clearing & preparation",
      "Grading & leveling",
      "Trenching for utilities",
      "Foundation excavation",
      "Pond & water feature excavation",
      "Demolition & removal",
      "Stump removal",
      "Bulk material hauling",
    ],
    images: [
      "/images/Excavation-1920w.jpg",
      "/images/Excavation+project-1920w.jpg",
      "/images/Retaining+wall+land+prep-1920w.jpg",
    ],
    heroImage: "/images/Excavation-1920w.jpg",
  },
  {
    title: "Material Delivery",
    slug: "material-delivery",
    icon: Package,
    shortDescription: "Gravel, soil, bark, rock, and sand delivered to your site.",
    description: "Save time and money with our convenient material delivery service. We deliver a wide range of landscaping and construction materials directly to your project site. From topsoil and gravel to bark mulch and decorative rock, we have the materials you need and the trucks to get them there on time.",
    features: [
      "Topsoil & garden soil",
      "Gravel & crushed rock",
      "Bark mulch & wood chips",
      "Sand & fill material",
      "Decorative rock & stone",
      "Compost & amendments",
      "Same-day delivery available",
      "Competitive pricing",
    ],
    images: [
      "/images/Sunrise+Landscape+dumptruck-1920w.jpg",
      "/images/Sunrise+Landscape+Contractor+trucks-1920w.jpg",
      "/images/Sunrise-2BLandscape-2Btrucks-1920w.jpg",
    ],
    heroImage: "/images/Sunrise+Landscape+dumptruck-1920w.jpg",
  },
];

export const SERVICE_AREAS = [
  {
    city: "Marysville",
    slug: "marysville",
    state: "WA",
    description: "Based in Marysville, we are your local landscaping and general contracting experts. As our home base, Marysville residents enjoy fast response times and deep knowledge of local soil conditions, climate, and building codes.",
    zip: "98270",
  },
  {
    city: "Everett",
    slug: "everett",
    state: "WA",
    description: "Serving Everett with professional landscaping, hardscaping, and general contracting services. From waterfront properties to hillside homes, we understand the unique challenges of landscaping in Everett.",
    zip: "98201",
  },
  {
    city: "Arlington",
    slug: "arlington",
    state: "WA",
    description: "Arlington homeowners trust Sunrise Landscape for quality landscape design, retaining walls, and excavation work. We serve the entire Arlington area with reliable, professional contracting services.",
    zip: "98223",
  },
  {
    city: "Lake Stevens",
    slug: "lake-stevens",
    state: "WA",
    description: "Lake Stevens properties deserve beautiful landscapes. We provide comprehensive landscaping, drainage solutions, and outdoor living spaces designed for the Lake Stevens lifestyle.",
    zip: "98258",
  },
  {
    city: "Stanwood",
    slug: "stanwood",
    state: "WA",
    description: "Serving the Stanwood-Camano area with expert landscaping and contracting services. From rural acreage to residential properties, we handle projects of all sizes in Stanwood.",
    zip: "98292",
  },
  {
    city: "Mill Creek",
    slug: "mill-creek",
    state: "WA",
    description: "Mill Creek's planned community deserves top-tier landscaping. We specialize in creating beautiful, HOA-compliant landscapes and outdoor living spaces for Mill Creek homeowners.",
    zip: "98012",
  },
  {
    city: "Snohomish",
    slug: "snohomish",
    state: "WA",
    description: "The historic city of Snohomish is one of our core service areas. We provide landscaping, hardscaping, and excavation services that complement Snohomish's charming character.",
    zip: "98290",
  },
  {
    city: "Kirkland",
    slug: "kirkland",
    state: "WA",
    description: "We extend our premium landscaping and contracting services to Kirkland. From lakeside properties to residential neighborhoods, we bring the same quality craftsmanship to every Kirkland project.",
    zip: "98033",
  },
];

export const TESTIMONIALS = [
  {
    name: "Michael R.",
    location: "Marysville, WA",
    text: "Sunrise Landscape transformed our backyard with a stunning retaining wall and new garden beds. The team was professional, on time, and the quality of work exceeded our expectations. Highly recommend!",
    rating: 5,
  },
  {
    name: "Jennifer S.",
    location: "Lake Stevens, WA",
    text: "We had major drainage issues in our yard that were threatening our foundation. Sunrise installed a French drain system that solved the problem completely. Great communication throughout the project.",
    rating: 5,
  },
  {
    name: "David & Maria L.",
    location: "Everett, WA",
    text: "Had our pool completely restored by Sunrise — new tile, resurfacing, and a beautiful new deck. It looks brand new! They were one of the only contractors in the area who could handle pool work.",
    rating: 5,
  },
  {
    name: "Sarah K.",
    location: "Arlington, WA",
    text: "From excavation to the final landscaping touches, Sunrise handled our entire property renovation. The crew was hardworking, respectful, and delivered outstanding results on budget.",
    rating: 5,
  },
  {
    name: "Tom & Lisa P.",
    location: "Snohomish, WA",
    text: "We needed a large retaining wall to create a usable backyard on our sloped lot. Sunrise engineered and built a wall that not only solved our problem but looks amazing. Five stars!",
    rating: 5,
  },
  {
    name: "Robert H.",
    location: "Mill Creek, WA",
    text: "Sunrise delivered several loads of topsoil and bark for our landscaping project. On time, fair pricing, and the materials were top quality. Will definitely use them again.",
    rating: 5,
  },
];

export const GALLERY_IMAGES = [
  { src: "/images/curved+retaining+wall-1920w.jpg", alt: "Curved retaining wall installation", category: "Retaining Walls" },
  { src: "/images/curved+retaining+walls-1920w.jpg", alt: "Decorative curved retaining walls", category: "Retaining Walls" },
  { src: "/images/retaining+wall+beds-1920w.jpg", alt: "Retaining wall with garden beds", category: "Retaining Walls" },
  { src: "/images/Retaining+wall+land+prep-1920w.jpg", alt: "Retaining wall land preparation", category: "Retaining Walls" },
  { src: "/images/new+landscaping+design-1920w.jpg", alt: "New landscaping design", category: "Landscaping" },
  { src: "/images/new+garden+beds-1920w.jpg", alt: "New garden bed installation", category: "Landscaping" },
  { src: "/images/landscape+digging-ff70d53c-1920w.jpg", alt: "Landscape excavation work", category: "Landscaping" },
  { src: "/images/stone+pathways-1920w.jpg", alt: "Stone pathway installation", category: "Hardscaping" },
  { src: "/images/Pool+Before-1920w.jpg", alt: "Pool before restoration", category: "Pool Restoration", beforeAfter: "before" },
  { src: "/images/Pool+After-1920w.jpg", alt: "Pool after restoration", category: "Pool Restoration", beforeAfter: "after" },
  { src: "/images/pool+restoration+services-1920w.jpg", alt: "Pool restoration in progress", category: "Pool Restoration" },
  { src: "/images/pool+tile-1920w.jpg", alt: "Pool tile installation", category: "Pool Restoration" },
  { src: "/images/swimming+pool+restoration+services-1920w.jpg", alt: "Swimming pool restoration", category: "Pool Restoration" },
  { src: "/images/Spa+Before-1920w.jpg", alt: "Spa before restoration", category: "Pool Restoration", beforeAfter: "before" },
  { src: "/images/Spa+After-b9408c57-1920w.jpg", alt: "Spa after restoration", category: "Pool Restoration", beforeAfter: "after" },
  { src: "/images/Excavation-1920w.jpg", alt: "Excavation project", category: "Excavation" },
  { src: "/images/Excavation+project-1920w.jpg", alt: "Large excavation project", category: "Excavation" },
  { src: "/images/Sunrise+Landscape+Contractor+trucks-1920w.jpg", alt: "Sunrise Landscape contractor trucks", category: "Equipment" },
  { src: "/images/Sunrise+Landscape+dumptruck-1920w.jpg", alt: "Sunrise Landscape dump truck", category: "Equipment" },
  { src: "/images/Sunrise-2BLandscape-2Btrucks-1920w.jpg", alt: "Sunrise Landscape fleet", category: "Equipment" },
  { src: "/images/g-1-1363w.jpg", alt: "Completed hardscaping project", category: "Hardscaping" },
  { src: "/images/g2-1363w.jpg", alt: "Outdoor living space", category: "Hardscaping" },
  { src: "/images/g3-1363w.jpg", alt: "Concrete work project", category: "Concrete" },
  { src: "/images/g4-1363w.jpg", alt: "Finished concrete installation", category: "Concrete" },
  { src: "/images/img-2-433w.jpg", alt: "Landscaping project detail", category: "Landscaping" },
  { src: "/images/img-3-433w.jpg", alt: "Garden design detail", category: "Landscaping" },
  { src: "/images/img-4-527w.jpg", alt: "Outdoor project detail", category: "Hardscaping" },
  { src: "/images/img-5-1920w.jpg", alt: "Project in progress", category: "Concrete" },
  { src: "/images/img-6-1920w.jpg", alt: "Paver walkway project", category: "Hardscaping" },
  { src: "/images/img-7-1920w.jpg", alt: "Completed outdoor project", category: "Hardscaping" },
];

export const BEFORE_AFTER_PAIRS = [
  {
    before: "/images/Pool+Before-1920w.jpg",
    after: "/images/Pool+After-1920w.jpg",
    title: "Pool Restoration",
    description: "Complete pool resurfacing and tile replacement",
  },
  {
    before: "/images/Spa+Before-1920w.jpg",
    after: "/images/Spa+After-b9408c57-1920w.jpg",
    title: "Spa Renovation",
    description: "Full spa restoration with new tile and finish",
  },
];

// Nav links split into left and right for centered logo layout
export const NAV_LINKS_LEFT = [
  { href: "/", label: "Home" },
  { href: "/landscape", label: "Landscape", hasDropdown: true },
  { href: "/pool-restoration", label: "Pool Restoration" },
];

export const NAV_LINKS_RIGHT = [
  { href: "/photo-gallery", label: "Photo Gallery" },
  { href: "/contact-us", label: "Contact Us" },
];

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/landscape", label: "Landscape" },
  { href: "/pool-restoration", label: "Pool Restoration" },
  { href: "/photo-gallery", label: "Photo Gallery" },
  { href: "/contact-us", label: "Contact Us" },
];

// Landscape dropdown sub-items
export const LANDSCAPE_DROPDOWN = [
  { href: "/landscape", label: "Landscaping" },
  { href: "/hardscape", label: "Hardscaping" },
  { href: "/drainage", label: "Drainage Systems" },
  { href: "/material-delivery", label: "Material Delivery" },
];

export const SERVICE_AREA_ZIPS: Record<string, string> = {
  "98270": "Marysville",
  "98271": "Marysville",
  "98201": "Everett",
  "98203": "Everett",
  "98204": "Everett",
  "98205": "Everett",
  "98206": "Everett",
  "98207": "Everett",
  "98208": "Everett",
  "98223": "Arlington",
  "98258": "Lake Stevens",
  "98292": "Stanwood",
  "98012": "Mill Creek",
  "98290": "Snohomish",
  "98296": "Snohomish",
  "98033": "Kirkland",
  "98034": "Kirkland",
  "98272": "Granite Falls",
  "98252": "Index",
  "98241": "Darrington",
  "98294": "Sultan",
};
